### create user

POST http://localhost:8222/user/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fullname": "Praveen Ukkoji",
  "email": "praveen@gmail.com",
  "password": "dondon"
}